"""initial_schema

Revision ID: 88264ac1bfd6
Revises: 
Create Date: 2026-02-15 11:55:50.508501

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88264ac1bfd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('role_title', sa.Text(), nullable=True),
    sa.Column('jd_raw', sa.Text(), nullable=False),
    sa.Column('jd_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jd_source', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('include_report', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("jd_source IN ('paste', 'screenshot', 'url')", name='ck_applications_jd_source'),
    sa.CheckConstraint("status IN ('draft', 'tailoring', 'review', 'complete')", name='ck_applications_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('name_confidence', sa.Float(), nullable=True),
    sa.Column('contact_confidence', sa.Float(), nullable=True),
    sa.Column('unstructured_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_text_quality', sa.Float(), nullable=True),
    sa.Column('parsing_status', sa.Text(), nullable=False),
    sa.Column('parsing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("file_type IN ('pdf', 'docx', 'paste')", name='ck_cv_uploads_file_type'),
    sa.CheckConstraint("parsing_status IN ('pending', 'partial', 'complete', 'failed')", name='ck_cv_uploads_parsing_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('proficiency', sa.Text(), nullable=True),
    sa.Column('domain_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_duplicate_of', sa.UUID(), nullable=True),
    sa.CheckConstraint("category IN ('technical', 'language', 'tool', 'soft', 'other', 'certification', 'framework')", name='ck_skills_category'),
    sa.ForeignKeyConstraint(['is_duplicate_of'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tailoring_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('selected_experiences', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('selected_education', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('selected_projects', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('selected_skills', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('diff_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejected_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_cv_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('docx_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_source_id', sa.UUID(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('degree', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_block', sa.Text(), nullable=False),
    sa.Column('dates_confidence', sa.Float(), nullable=True),
    sa.Column('institution_confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['upload_source_id'], ['cv_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_source_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_block', sa.Text(), nullable=False),
    sa.Column('domain_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('skill_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('variant_group_id', sa.UUID(), nullable=True),
    sa.Column('is_primary_variant', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['upload_source_id'], ['cv_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unclassified_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_source_id', sa.UUID(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('gpt_category_guess', sa.Text(), nullable=True),
    sa.Column('gpt_confidence', sa.Float(), nullable=True),
    sa.Column('user_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_as', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upload_source_id'], ['cv_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_source_id', sa.UUID(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('role_title', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('company_confidence', sa.Float(), nullable=True),
    sa.Column('dates_confidence', sa.Float(), nullable=True),
    sa.Column('bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_block', sa.Text(), nullable=False),
    sa.Column('domain_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('skill_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('variant_group_id', sa.UUID(), nullable=True),
    sa.Column('is_primary_variant', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('user_corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['upload_source_id'], ['cv_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experiences')
    op.drop_table('unclassified_blocks')
    op.drop_table('projects')
    op.drop_table('education')
    op.drop_table('cv_versions')
    op.drop_table('tailoring_rules')
    op.drop_table('skills')
    op.drop_table('cv_uploads')
    op.drop_table('cv_profiles')
    op.drop_table('applications')
    # ### end Alembic commands ###
